server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: transaction-service
  neo4j:
    uri: bolt://localhost:7687/
    authentication:
      username: neo4j
      password: 12345678
